apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "6g-simulation.fullname" . }}
  labels:
    {{- include "6g-simulation.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "6g-simulation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "6g-simulation.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: 6g-simulation-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
